version: "3"
services:
  react_native:
    build: ./container/react_native
    volumes:
      - ./react_native/:/usr/src/app
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    tty: true
    stdin_open: true
    command: yarn start
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"